instance BAN_9001_Roland (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Roland";
Npctype = NPCTYPE_GUARD;
guild = GIL_NONE;
level = 21;
voice = 12;
id = 9001;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 70;
attribute[ATR_DEXTERITY] = 70;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 220;
attribute[ATR_HITPOINTS] = 220;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 0,"Hum_Head_FatBald",91, 1,VLK_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,1);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_Old_01);
EquipItem		(self, ItRw_Bow_Small_01);
CreateInvItems  (self,ItFoLoaf,2);
CreateInvItems  (self,ItFoBooze,2);
CreateInvItems  (self,ItFo_Potion_Health_01,2);
CreateInvItems  (self,ItMiNugget,50);
CreateInvItems  (self,ItAmArrow,50);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_9001;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_9001 ()
{
TA_Boss (08,00,18,00,"WP_MOD_000");
TA_SitAround (18,00,24,00,"WP_MOD_003");
TA_Sleep (24,00,08,00,"WP_MOD_006");
};
